[package]
name = "paper-log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Renderer file and stderr tracing for skwd-paper"

[dependencies]
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

[lints]
workspace = true
